apiVersion: v1
kind: Service
metadata:
  name: www
spec:
  selector:
    app: projet-www
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
