apiVersion: apps/v1
kind: Deployment
metadata:
  name: projet-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projet-db
  template:
    metadata:
      labels:
        app: projet-db
    spec:
      containers:
        - name: db
          image: unboundedtechnologies/projet-db
          env:
            - name: MYSQL_DATABASE
              value: php_docker
            - name: MYSQL_USER
              value: php_docker
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - containerPort: 3306